services:
  postgres:
    container_name: postgres-sql-olms
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - usr-mgmnt
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-olms
    image: maildev/maildev
    ports:
      - 1080:1080  # Web interface Maildev
      - 1025:1025  #  SMTP port
    networks:
      - usr-mgmnt
    restart: unless-stopped

networks:
  usr-mgmnt:
    driver: bridge

volumes:
  postgres:
    driver: local
